-- ============================================
-- Web Solution - Oracle DB 초기화 스크립트
-- ============================================

-- 1. 권한 그룹
CREATE TABLE ROLE_GROUPS (
  ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME          VARCHAR2(100)  NOT NULL,
  DESCRIPTION   VARCHAR2(500),
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 2. 사용자
CREATE TABLE USERS (
  ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USERNAME        VARCHAR2(50)   NOT NULL UNIQUE,
  PASSWORD_HASH   VARCHAR2(200)  NOT NULL,
  NAME            VARCHAR2(100)  NOT NULL,
  EMAIL           VARCHAR2(200),
  ROLE_GROUP_ID   NUMBER         REFERENCES ROLE_GROUPS(ID),
  IS_ACTIVE       NUMBER(1)      DEFAULT 1,
  CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP
);

-- 3. 메뉴 (계층 구조 지원)
CREATE TABLE MENUS (
  ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME          VARCHAR2(200)  NOT NULL,
  DESCRIPTION   VARCHAR2(500),
  ORDER_NUM     NUMBER         DEFAULT 0,
  MENU_TYPE     VARCHAR2(20)   DEFAULT 'menu',      -- 'folder' | 'menu'
  PARENT_ID     NUMBER         REFERENCES MENUS(ID) ON DELETE SET NULL,
  IS_RELEASED   NUMBER(1)      DEFAULT 0,           -- 1 = 사용자 화면 노출
  LAYOUT_JSON   CLOB,
  CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP
);

-- 4. 메뉴별 권한
CREATE TABLE ROLE_PERMISSIONS (
  ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ROLE_GROUP_ID   NUMBER NOT NULL REFERENCES ROLE_GROUPS(ID) ON DELETE CASCADE,
  MENU_ID         NUMBER NOT NULL REFERENCES MENUS(ID) ON DELETE CASCADE,
  CAN_READ        NUMBER(1) DEFAULT 1,
  CAN_WRITE       NUMBER(1) DEFAULT 0,
  CAN_DELETE      NUMBER(1) DEFAULT 0,
  CONSTRAINT UQ_ROLE_MENU UNIQUE (ROLE_GROUP_ID, MENU_ID)
);

-- 5. 데이터 소스 (차트/그리드용 동적 데이터 쿼리 저장)
CREATE TABLE DATA_SOURCES (
  ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME          VARCHAR2(200)  NOT NULL,
  DESCRIPTION   VARCHAR2(500),
  QUERY_TEXT    CLOB           NOT NULL,
  CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP
);

-- ============================================
-- 초기 데이터
-- ============================================

-- 기본 권한 그룹
INSERT INTO ROLE_GROUPS (NAME, DESCRIPTION) VALUES ('관리자', '시스템 전체 관리 권한');
INSERT INTO ROLE_GROUPS (NAME, DESCRIPTION) VALUES ('일반사용자', '조회 권한');
INSERT INTO ROLE_GROUPS (NAME, DESCRIPTION) VALUES ('매니저', '조회 및 수정 권한');

-- 기본 관리자 계정 (비밀번호: admin123 - bcrypt hash)
-- 실제 hash 값은 애플리케이션에서 /api/auth/register 호출로 생성
INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, ROLE_GROUP_ID)
VALUES ('admin', '$2a$10$placeholder_hash_replace_via_register_api', '관리자', 'admin@company.com', 1);

-- 샘플 데이터 소스
INSERT INTO DATA_SOURCES (NAME, DESCRIPTION, QUERY_TEXT) VALUES (
  '월별 매출',
  '월별 매출, 목표, 이익 데이터',
  'SELECT MONTH_NAME AS "month", SALES AS "sales", TARGET AS "target", PROFIT AS "profit" FROM MONTHLY_SALES ORDER BY MONTH_NO'
);

INSERT INTO DATA_SOURCES (NAME, DESCRIPTION, QUERY_TEXT) VALUES (
  '직원 목록',
  '직원 관리 그리드용 데이터',
  'SELECT ID, NAME AS "name", DEPARTMENT AS "department", POSITION AS "position", EMAIL AS "email", JOIN_DATE AS "joinDate", SALARY AS "salary", STATUS AS "status" FROM EMPLOYEES ORDER BY ID'
);

INSERT INTO DATA_SOURCES (NAME, DESCRIPTION, QUERY_TEXT) VALUES (
  '지역별 매출',
  '지역/제품별 분기 매출 데이터',
  'SELECT REGION AS "region", PRODUCT AS "product", Q1 AS "q1", Q2 AS "q2", Q3 AS "q3", Q4 AS "q4", (Q1+Q2+Q3+Q4) AS "total" FROM REGIONAL_SALES ORDER BY REGION, PRODUCT'
);

COMMIT;
